# Configuration for ReTA Hyperparameters

# --- Positive Cache Configuration ---
positive:
  enabled: True
  shot_capacity: 3
  alpha: 15.0
  beta: 5.0 
  lam: 0.3 
  ratio: 1.0

learning_rate:
  text: 0.0003 
  align: 0.3
  train_w: 0.01 