# Configuration for ReTA Hyperparameters

# --- Positive Cache Configuration ---
positive:
  enabled: True
  shot_capacity: 3
  alpha: 7.0
  beta: 2.0 
  lam: 0.5
  ratio: 1.0

learning_rate:
  text: 0.0003 
  align: 0.6
  train_w: 0.04