# Configuration for ReTA Hyperparameters

# --- Positive Cache Configuration ---
positive:
  enabled: True
  shot_capacity: 3
  alpha: 5.0
  beta: 7.45 
  lam: 0.2
  ratio: 1.0

learning_rate:
  text: 0.0008
  align: 0.2
  train_w: 0.02